trigger: 
- main

stages:
- stage: BuildDeploy
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
      
    steps: 
    
     - task: Npm@1
       inputs:
         command: 'install'
    
     - task: Npm@1
       inputs:
         command: 'custom'
         customCommand: 'run build'
       env:
         VITE_BASE_URL: 'http://68.178.165.107:5001/api/'

     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'dist'
         publishLocation: 'Container'

     # Stop the IIS site before copying files
     - task: SSH@0
       inputs:
         sshEndpoint: 'newvm'
         runOptions: 'commands'
         commands: '"C:\Windows\System32\inetsrv\appcmd.exe" stop site /site.name:"land_bank_fe"'
         readyTimeout: '30000'

     # Add a delay of 30 seconds to avoid conflicts
     - script: |
         sleep 15
       displayName: 'Wait for 30 seconds'

     # Copy files to the target server
     - task: CopyFilesOverSSH@0
       inputs:
         sshEndpoint: 'newvm'
         sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
         contents: '**'
         targetFolder: '/inetpub/wwwroot/LAND_BANK_FE'
         readyTimeout: '30000'

     # Add another delay before starting the IIS site to ensure files are properly copied
     - script: |
         sleep 15
       displayName: 'Wait for 30 seconds before starting IIS'

     # Start the IIS site after files are copied
     - task: SSH@0
       inputs:
         sshEndpoint: 'newvm'
         runOptions: 'commands'
         commands: '"C:\Windows\System32\inetsrv\appcmd.exe" start site /site.name:"land_bank_fe"'
         readyTimeout: '30000'
